-- JSOS 40-theme curriculum v2.0. Each theme owns stable, selectable scenes.
-- Preserve templates referenced by existing tasks, but move the prior ordering
-- out of the way and disable entries that are no longer part of v2.0.
with order_offset as (
  select coalesce(max(abs(original_order)), 0) + 1000 as value
  from public.curriculum_templates
)
update public.curriculum_templates
set original_order = original_order + order_offset.value,
    enabled = false
from order_offset;

insert into public.curriculum_templates (stable_key, original_order, stage, topic, scenario, target_patterns) values
('life_convenience_supermarket',1,1,'便利店与超市','{"scenes":[{"key":"find_compare","title":"找商品与比较","roles":["店员","顾客"],"goals":["询问位置","确认差异"]},{"key":"checkout_member","title":"结账与会员卡","roles":["收银员","顾客"],"goals":["选择支付","使用积分"]},{"key":"price_problem","title":"处理价格问题","roles":["店员","顾客"],"goals":["说明差异","确认处理"]}]}','["〜はどこにありますか","こちらと何が違いますか","確認していただけますか"]'),
('life_dining',2,1,'外食','{"scenes":[{"key":"order_customize","title":"点单与定制","roles":["店员","顾客"],"goals":["询问推荐","修改要求"]},{"key":"late_wrong_order","title":"催餐与订单错误","roles":["店员","顾客"],"goals":["说明问题","提出处理请求"]},{"key":"payment_takeout","title":"结账与外带","roles":["店员","顾客"],"goals":["分别结账","确认打包"]}]}','["おすすめは何ですか","〜に変更できますか","別々にお願いします"]'),
('life_transit',3,1,'电车、车站与公交','{"scenes":[{"key":"route_transfer","title":"路线与换乘","roles":["站务员","乘客"],"goals":["询问路线","确认站台"]},{"key":"delay_wrong_train","title":"延误与坐错车","roles":["站务员","乘客"],"goals":["说明情况","寻找替代路线"]},{"key":"ticket_card","title":"车票与交通卡","roles":["站务员","乘客"],"goals":["购票","处理交通卡问题"]}]}','["〜へはどう行けばいいですか","どこで乗り換えますか","別の行き方はありますか"]'),
('life_directions_taxi',4,1,'问路与出租车','{"scenes":[{"key":"ask_directions","title":"步行问路","roles":["路人","行人"],"goals":["询问位置","复述路线"]},{"key":"taxi_destination","title":"出租车目的地","roles":["司机","乘客"],"goals":["说明目的地","指定下车位置"]},{"key":"route_payment","title":"路线与支付问题","roles":["司机","乘客"],"goals":["确认路线","处理支付"]}]}','["〜までどう行けばいいですか","ここで降ろしてください","この道で合っていますか"]'),
('life_airport',5,1,'机场与航班','{"scenes":[{"key":"checkin_baggage","title":"值机与托运行李","roles":["地勤人员","旅客"],"goals":["办理值机","确认行李规定"]},{"key":"security_boarding","title":"安检、出境与登机","roles":["工作人员","旅客"],"goals":["确认流程","寻找登机口"]},{"key":"disruption_baggage","title":"延误、取消与行李异常","roles":["航空公司人员","旅客"],"goals":["说明问题","确认替代安排"]}]}','["チェックインをお願いします","搭乗口はどこですか","振り替え便を確認したいです"]'),
('life_shopping_returns',6,1,'购物与退换货','{"scenes":[{"key":"size_stock","title":"尺寸与库存","roles":["店员","顾客"],"goals":["找尺寸","确认库存"]},{"key":"compare_try","title":"比较与试用","roles":["店员","顾客"],"goals":["比较商品","请求试用"]},{"key":"return_exchange","title":"退货与换货","roles":["店员","顾客"],"goals":["说明原因","确认条件"]}]}','["別のサイズはありますか","試してもいいですか","返品したいのですが"]'),
('life_pharmacy',7,1,'药店','{"scenes":[{"key":"symptom_medicine","title":"症状与选药","roles":["药剂师","顾客"],"goals":["描述症状","询问药品"]},{"key":"usage_warning","title":"用法与注意事项","roles":["药剂师","顾客"],"goals":["确认用量","确认禁忌"]},{"key":"alternative","title":"寻找替代药品","roles":["药剂师","顾客"],"goals":["说明限制","比较替代品"]}]}','["〜に効く薬はありますか","一日に何回飲みますか","一緒に飲んでも大丈夫ですか"]'),
('life_medical',8,1,'医院、诊所与牙科','{"scenes":[{"key":"registration","title":"挂号与预约","roles":["前台","患者"],"goals":["说明就诊原因","预约时间"]},{"key":"consultation","title":"问诊与检查","roles":["医生","患者"],"goals":["描述症状","回答追问"]},{"key":"followup","title":"结果与复诊","roles":["医生","患者"],"goals":["确认结果","预约复诊"]}]}','["〜が痛いです","いつからですか","次はいつ来ればいいですか"]'),
('life_hotel',9,1,'酒店与临时住宿','{"scenes":[{"key":"checkin","title":"入住与设施","roles":["前台","住客"],"goals":["确认预约","询问设施"]},{"key":"room_problem","title":"房间问题","roles":["前台","住客"],"goals":["说明故障","请求处理"]},{"key":"checkout","title":"退房与费用","roles":["前台","住客"],"goals":["确认账单","寄存行李"]}]}','["予約している〜です","確認していただけますか","荷物を預かっていただけますか"]'),
('life_delivery_post',10,1,'快递与邮局','{"scenes":[{"key":"send_package","title":"寄送包裹","roles":["窗口人员","顾客"],"goals":["选择寄送方式","确认费用"]},{"key":"redelivery","title":"改期与再配送","roles":["客服","收件人"],"goals":["确认包裹","变更时间"]},{"key":"missing_delivery","title":"未送达处理","roles":["客服","收件人"],"goals":["说明情况","确认调查结果"]}]}','["〜まで送りたいです","配達日時を変更したいです","まだ届いていません"]'),
('life_library',11,1,'图书馆','{"scenes":[{"key":"library_card","title":"办理借阅证","roles":["馆员","读者"],"goals":["询问材料","了解规则"]},{"key":"find_borrow","title":"找书与借阅","roles":["馆员","读者"],"goals":["检索书籍","办理借阅"]},{"key":"renew_reserve","title":"续借与预约","roles":["馆员","读者"],"goals":["申请续借","预约借出图书"]}]}','["利用カードを作りたいです","この本を探しています","貸出期間を延長できますか"]'),
('life_sports_facility',12,1,'游泳馆与健身房','{"scenes":[{"key":"membership","title":"办卡与费用","roles":["工作人员","用户"],"goals":["比较方案","确认费用"]},{"key":"rules_equipment","title":"设施与使用规则","roles":["工作人员","用户"],"goals":["询问泳道","了解器材规则"]},{"key":"class_booking","title":"课程预约与取消","roles":["工作人员","用户"],"goals":["预约课程","变更预约"]}]}','["初めて利用します","〜を使ってもいいですか","予約を変更したいです"]'),
('life_salon',13,1,'理发店与美容服务','{"scenes":[{"key":"booking","title":"预约服务","roles":["店员","顾客"],"goals":["确认项目","预约时间"]},{"key":"style_request","title":"说明需求","roles":["理发师","顾客"],"goals":["描述长度","说明风格"]},{"key":"adjustment","title":"过程中调整","roles":["理发师","顾客"],"goals":["提出修改","确认效果"]}]}','["予約をお願いしたいです","〜ぐらいに切ってください","もう少し短くできますか"]'),
('life_mobile_internet',14,1,'手机、网络与电子设备','{"scenes":[{"key":"plan_contract","title":"套餐与签约","roles":["店员","顾客"],"goals":["比较套餐","确认费用"]},{"key":"network_problem","title":"网络故障","roles":["客服","用户"],"goals":["描述故障","完成排查"]},{"key":"repair_cancel","title":"维修与解约","roles":["店员","用户"],"goals":["询问维修","确认解约条件"]}]}','["契約内容を確認したいです","インターネットにつながりません","解約するといくらかかりますか"]'),
('life_home_repair',15,1,'住房、水电燃气与报修','{"scenes":[{"key":"utilities_start_stop","title":"开通与停用水电燃气","roles":["客服","住户"],"goals":["申请开通或停用","确认日期与手续"]},{"key":"fault_appointment","title":"故障与预约维修","roles":["维修人员","住户"],"goals":["描述故障","协调上门时间"]},{"key":"bill_responsibility","title":"账单、费用与责任确认","roles":["管理公司","住户"],"goals":["确认账单","确认费用责任"]}]}','["利用開始の手続きをしたいです","いつ来ていただけますか","この料金について確認したいです"]'),
('life_neighbors_waste',16,2,'邻里、垃圾与社区规则','{"scenes":[{"key":"greeting_notice","title":"邻里问候与通知","roles":["邻居","住户"],"goals":["自我介绍","传达通知"]},{"key":"waste_rules","title":"垃圾分类","roles":["管理员","住户"],"goals":["询问分类","确认投放时间"]},{"key":"noise","title":"噪音沟通","roles":["邻居","住户"],"goals":["礼貌说明","协商解决"]}]}','["引っ越してきた〜です","これは何ごみですか","少し音が気になるのですが"]'),
('settle_city_hall',17,2,'市役所与行政手续','{"scenes":[{"key":"resident_registration","title":"住民登记","roles":["窗口人员","居民"],"goals":["说明办理事项","提交材料"]},{"key":"certificate","title":"申请证明文件","roles":["窗口人员","居民"],"goals":["选择文件","确认用途"]},{"key":"form_help","title":"表格与补充材料","roles":["窗口人员","居民"],"goals":["询问填写方法","处理材料不足"]}]}','["〜の手続きをしたいです","必要な書類は何ですか","書き方を教えていただけますか"]'),
('settle_renting_moving',18,2,'租房与搬家','{"scenes":[{"key":"viewing","title":"看房与条件","roles":["中介","租客"],"goals":["确认设施","询问条件"]},{"key":"cost_contract","title":"费用与合同","roles":["中介","租客"],"goals":["确认初期费用","理解条款"]},{"key":"movein_check","title":"入住检查","roles":["管理公司","住户"],"goals":["报告损坏","确认钥匙和规则"]}]}','["初期費用はいくらですか","この条件について確認したいです","入居前から傷があります"]'),
('settle_bank_payment',19,2,'银行与日常支付','{"scenes":[{"key":"open_account","title":"开户","roles":["银行职员","客户"],"goals":["说明用途","提交材料"]},{"key":"transfer_card","title":"转账与银行卡","roles":["银行职员","客户"],"goals":["办理转账","处理银行卡问题"]},{"key":"payment_error","title":"扣款异常","roles":["客服","客户"],"goals":["说明异常","确认处理时间"]}]}','["口座を開設したいです","振り込みたいです","身に覚えのない引き落としがあります"]'),
('settle_tax_insurance',20,2,'税金、保险与年金','{"scenes":[{"key":"system_question","title":"制度咨询","roles":["窗口人员","居民"],"goals":["确认适用制度","了解缴费"]},{"key":"submit_documents","title":"提交材料","roles":["窗口人员","居民"],"goals":["确认文件","补充缺失内容"]},{"key":"notice_problem","title":"通知与缴费问题","roles":["窗口人员","居民"],"goals":["解释通知","处理逾期或重复"]}]}','["この通知について教えてください","私も対象になりますか","支払い状況を確認したいです"]'),
('settle_police_lost',21,2,'警察与遗失物','{"scenes":[{"key":"lost_item","title":"交番报失","roles":["警察","失主"],"goals":["描述物品","说明时间地点"]},{"key":"theft_report","title":"报案","roles":["警察","报案人"],"goals":["说明经过","回答追问"]},{"key":"found_item","title":"领取失物","roles":["工作人员","失主"],"goals":["确认身份","核对物品"]}]}','["〜をなくしました","最後に見たのは〜です","遺失届を出したいです"]'),
('settle_emergency',22,2,'灾害与紧急情况','{"scenes":[{"key":"earthquake_evacuation","title":"地震与避难","roles":["工作人员","居民"],"goals":["确认安全","寻找避难地点"]},{"key":"call_emergency","title":"紧急报警","roles":["接线员","求助者"],"goals":["说明位置","描述情况"]},{"key":"help_others","title":"现场求助","roles":["路人","求助者"],"goals":["请求帮助","说明人员状态"]}]}','["避難所はどこですか","今いる場所は〜です","救急車をお願いします"]'),
('social_leisure',23,2,'休闲娱乐场所','{"scenes":[{"key":"ticket_booking","title":"购票与预约","roles":["工作人员","顾客"],"goals":["选择票种","确认时间"]},{"key":"venue_rules","title":"设施规则","roles":["工作人员","访客"],"goals":["询问拍照","确认入场规则"]},{"key":"change_refund","title":"改期与退票","roles":["客服","顾客"],"goals":["说明原因","确认处理条件"]}]}','["チケットを予約したいです","写真を撮ってもいいですか","時間を変更できますか"]'),
('social_smalltalk',24,2,'天气、兴趣与日常闲聊','{"scenes":[{"key":"weather_season","title":"天气与季节","roles":["同事","用户"],"goals":["开启话题","表达感受"]},{"key":"hobby_weekend","title":"兴趣与周末","roles":["朋友","用户"],"goals":["介绍兴趣","进行追问"]},{"key":"travel_food","title":"旅行与饮食","roles":["同事","用户"],"goals":["分享经历","回应推荐"]}]}','["最近どうですか","週末は何をしましたか","〜に興味があります"]'),
('social_plans',25,2,'邀请、约时间与婉拒','{"scenes":[{"key":"invite","title":"发出与回应邀请","roles":["朋友","用户"],"goals":["提出邀请","确认意愿"]},{"key":"schedule_change","title":"确认时间与改期","roles":["朋友","用户"],"goals":["协调时间","提出替代日期"]},{"key":"decline","title":"婉拒与道歉","roles":["同事","用户"],"goals":["礼貌拒绝","维持关系"]}]}','["一緒に〜ませんか","別の日でも大丈夫ですか","今回は難しそうです"]'),
('work_recruiting',26,3,'求职咨询与面试安排','{"scenes":[{"key":"role_inquiry","title":"职位咨询","roles":["招聘人员","求职者"],"goals":["确认职责","确认应聘条件"]},{"key":"schedule","title":"安排与调整面试","roles":["招聘人员","求职者"],"goals":["确认时间","礼貌改期"]},{"key":"preparation","title":"确认面试准备","roles":["招聘人员","求职者"],"goals":["确认形式","询问材料"]}]}','["業務内容について伺いたいです","面接日程を調整できますか","何を準備すればよいですか"]'),
('work_hr_interview',27,3,'HR 与经历面试','{"scenes":[{"key":"self_intro","title":"自我介绍与经历","roles":["面试官","候选人"],"goals":["概括经历","说明职责"]},{"key":"motivation","title":"动机与优势","roles":["面试官","候选人"],"goals":["说明动机","提供实例"]},{"key":"behavioral","title":"行为问题","roles":["面试官","候选人"],"goals":["描述困难","说明结果"]}]}','["これまで〜を担当しました","志望した理由は〜です","具体的には〜"]'),
('work_technical_interview',28,3,'技术面试','{"scenes":[{"key":"project","title":"介绍项目","roles":["技术面试官","候选人"],"goals":["说明架构","说明个人贡献"]},{"key":"decision","title":"技术选择","roles":["技术面试官","候选人"],"goals":["解释判断","比较方案"]},{"key":"problem_solving","title":"问题解决","roles":["技术面试官","候选人"],"goals":["分析问题","回答追问"]}]}','["この構成を選んだ理由は〜です","私が担当したのは〜です","課題は〜でした"]'),
('work_offer',29,3,'Offer 与入职条件','{"scenes":[{"key":"conditions","title":"确认工作条件","roles":["HR","候选人"],"goals":["确认薪资","确认工作方式"]},{"key":"start_date","title":"协商入职日期","roles":["HR","候选人"],"goals":["说明限制","提出日期"]},{"key":"contract_question","title":"合同疑问","roles":["HR","候选人"],"goals":["询问条款","确认书面信息"]}]}','["条件について確認したいです","入社日は〜を希望しています","こちらはどういう意味でしょうか"]'),
('work_onboarding',30,3,'入职与团队自我介绍','{"scenes":[{"key":"checkin","title":"报到与手续","roles":["HR","新员工"],"goals":["完成报到","确认流程"]},{"key":"team_intro","title":"团队自我介绍","roles":["团队成员","新员工"],"goals":["介绍背景","说明职责"]},{"key":"dev_environment","title":"开发环境与权限","roles":["同事","新员工"],"goals":["确认设置","请求权限"]}]}','["本日から入社しました〜です","〜を担当する予定です","権限を付与していただけますか"]'),
('work_task_clarification',31,3,'接受任务与确认要求','{"scenes":[{"key":"background_goal","title":"背景与目标","roles":["负责人","开发者"],"goals":["确认目的","复述理解"]},{"key":"acceptance_deadline","title":"完成标准与期限","roles":["负责人","开发者"],"goals":["确认范围","确认截止日期"]},{"key":"missing_information","title":"信息不足","roles":["负责人","开发者"],"goals":["指出缺口","请求补充"]}]}','["目的は〜という理解で合っていますか","完了条件を確認したいです","追加で〜が必要です"]'),
('work_standup',32,3,'晨会、电话与线上会议','{"scenes":[{"key":"normal_update","title":"常规进度同步","roles":["团队成员","开发者"],"goals":["汇报完成内容","说明今日计划"]},{"key":"remote_meeting","title":"电话和线上会议沟通","roles":["会议参与者","开发者"],"goals":["确认议题","表达意见"]},{"key":"clarify_blocker","title":"听不清、确认与阻塞问题","roles":["团队成员","开发者"],"goals":["请求重复或澄清","说明阻塞并请求帮助"]}]}','["昨日は〜を完了しました","もう一度説明していただけますか","〜で止まっています"]'),
('work_requirements',33,3,'需求与范围讨论','{"scenes":[{"key":"user_goal","title":"用户目标","roles":["产品经理","开发者"],"goals":["确认目标","澄清用户场景"]},{"key":"scope_priority","title":"范围与优先级","roles":["产品经理","开发者"],"goals":["区分范围","协商优先级"]},{"key":"change_request","title":"需求变更","roles":["产品经理","开发者"],"goals":["确认变更","说明影响"]}]}','["対象ユーザーは誰ですか","今回はどこまで対応しますか","変更による影響は〜です"]'),
('work_technical_design',34,3,'技术方案、演示与答疑','{"scenes":[{"key":"proposal","title":"说明技术方案","roles":["技术负责人","开发者"],"goals":["描述方案","解释流程与取舍"]},{"key":"demo_report","title":"演示功能或汇报结果","roles":["团队成员","开发者"],"goals":["说明演示步骤","总结结果"]},{"key":"questions_objections","title":"回答提问与异议","roles":["评审者","开发者"],"goals":["澄清问题","解释判断并回应异议"]}]}','["提案としては〜です","こちらの機能をご説明します","この判断にした理由は〜です"]'),
('work_estimation',35,3,'工时评估与排期','{"scenes":[{"key":"estimate","title":"工作量评估","roles":["负责人","开发者"],"goals":["说明拆分","给出估算"]},{"key":"dependency","title":"依赖与不确定性","roles":["负责人","开发者"],"goals":["指出依赖","说明风险"]},{"key":"schedule_negotiate","title":"协商排期","roles":["负责人","开发者"],"goals":["说明限制","提出新计划"]}]}','["〜日程度かかる見込みです","〜に依存しています","この日程では難しいです"]'),
('work_code_review',36,3,'Code Review','{"scenes":[{"key":"explain_change","title":"说明实现","roles":["评审者","开发者"],"goals":["解释修改","说明测试"]},{"key":"receive_feedback","title":"接收修改意见","roles":["评审者","开发者"],"goals":["确认意见","承诺修改"]},{"key":"disagree","title":"解释判断与异议","roles":["评审者","开发者"],"goals":["说明理由","寻求共识"]}]}','["この変更では〜しています","ご指摘の点を修正します","この実装にした理由は〜です"]'),
('work_incident',37,3,'Bug 与线上故障','{"scenes":[{"key":"report_bug","title":"报告与复现","roles":["测试人员","开发者"],"goals":["确认步骤","说明现象"]},{"key":"impact_cause","title":"影响与原因","roles":["负责人","开发者"],"goals":["说明范围","报告调查结果"]},{"key":"mitigation","title":"临时处理与升级","roles":["负责人","开发者"],"goals":["提出缓解方案","请求支援"]}]}','["再現手順は〜です","影響範囲は〜です","一時対応として〜します"]'),
('work_release',38,3,'测试、发布与回滚','{"scenes":[{"key":"test_result","title":"测试结果","roles":["QA","开发者"],"goals":["报告结果","确认剩余问题"]},{"key":"release_check","title":"发布确认","roles":["负责人","开发者"],"goals":["确认步骤","执行最终检查"]},{"key":"rollback","title":"异常与回滚","roles":["负责人","开发者"],"goals":["判断影响","提出回滚"]}]}','["テスト結果は〜です","リリースしても問題ありません","ロールバックを提案します"]'),
('work_risk_cross_team',39,3,'延期、风险与跨团队沟通','{"scenes":[{"key":"delay_report","title":"延期说明","roles":["负责人","开发者"],"goals":["说明原因","更新完成时间"]},{"key":"risk_escalation","title":"风险升级","roles":["经理","开发者"],"goals":["说明影响","请求决策"]},{"key":"cross_team","title":"跨团队协调","roles":["其他团队","开发者"],"goals":["确认依赖","协商交付"]}]}','["予定より遅れています","このままだと〜に影響します","〜までに対応していただけますか"]'),
('work_one_on_one',40,3,'1 on 1 与反馈','{"scenes":[{"key":"difficulty_support","title":"困难与支持","roles":["经理","员工"],"goals":["说明困难","请求支持"]},{"key":"feedback","title":"接收与表达反馈","roles":["经理","员工"],"goals":["确认反馈","提出看法"]},{"key":"career_goal","title":"职业目标","roles":["经理","员工"],"goals":["说明目标","讨论改进计划"]}]}','["最近困っていることは〜です","フィードバックをありがとうございます","今後は〜を目指したいです"]')
on conflict (stable_key) do update set
  original_order = excluded.original_order,
  stage = excluded.stage,
  topic = excluded.topic,
  scenario = excluded.scenario,
  target_patterns = excluded.target_patterns,
  enabled = true;
